### ISSUE TITLE
Should Vadi use generics?

### ISSUE THREAD

**Issue by nahuelwexd** [nahuelwexd/Vadi#2]
Currently Vadi tries to be as friendly as possible with C developers, but this itself causes the syntax to be a bit awkward for Vala developers, causing boilerplate code. See:

```vala
var app = (App) container.resolve (typeof (App));
```

This can be easily solved using generics, achieving a much more comfortable and easy to read syntax for Vala

```vala
var app = container.resolve<App> ();
```

But the problem with using generics is that it results in a somewhat cumbersome function to use in C, and almost impossible in other languages (in case someone wants to use this library in Javascript or Python for some strange reason)

```c
App* app = APP (vadi_container_resolve (container, TYPE_APP, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref));
```

Also, as you can see, 2 parameters are added to the function that don't end up being used.

So my question is... should Vadi drop support for these languages and start using generics? Should I keep 2 versions of each method, one with generics and one without? Should everything stay as it is today?

**Comment by desiderantes** [comment]
Other languages probably have a more streamlined IoC solution, and C devs... well, they are used to the pain, I guess.

**Comment by gavr123456789** [comment]
I completely agree with @desiderantes, you should make it as convenient as possible for Vala users, the rest langs already have their own IoC containers. And C GTK programmers have already chosen their way to write a huge amount of boilerplate xd.
